import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base='http://127.0.0.1:3001';
async function prepare(entry,region){await fetch(`${base}/api/prepare/${entry.id}?region=${region}`,{method:'POST'});for(let n=0;n<300;n++){const job=await (await fetch(`${base}/api/jobs/${encodeURIComponent(region+':'+entry.id)}`)).json();if(job.error)throw new Error(job.error);if(job.status==='ready')return job;await new Promise(r=>setTimeout(r,500));}throw new Error('个人剧情准备超时');}
const catalog=await(await fetch(base+'/api/catalog?region=jp&type=personal')).json();assert.ok(catalog.length>100);const card=catalog.find(e=>e.id==='card-1'),profile=catalog.find(e=>e.id==='profile-1');assert.ok(card&&profile);
const jobs=await Promise.all([prepare(card,'jp'),prepare(profile,'jp')]);for(const job of jobs){assert.ok(job.story.lines.length);assert.equal(job.missing.length,0,JSON.stringify(job.missing));assert.ok(job.story.live2d.length);}
const cnCatalog=await(await fetch(base+'/api/catalog?region=cn&type=personal')).json();
const cnJobs=await Promise.all(['card-1','profile-1'].map(id=>prepare(cnCatalog.find(e=>e.id===id),'cn')));
for(const job of cnJobs){assert.ok(job.story.lines.length);assert.equal(job.missing.length,0,JSON.stringify(job.missing));assert.equal(job.story.region,'cn');}jobs.push(...cnJobs);
const browser=await chromium.launch();
try{const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(({entry})=>{localStorage.setItem('sekai.resume',JSON.stringify({entry,region:'jp',index:0}));localStorage.setItem('sekai.settings',JSON.stringify({region:'jp',speed:0,performance:'eco',voice:0,bgm:0}));},{entry:card});await page.goto(base);await page.getByRole('button',{name:'继续故事',exact:true}).click();await page.locator('.dialogue').waitFor({timeout:60000});await page.waitForFunction(()=>Number(document.querySelector('.live2d-host')?.dataset.models)>0);assert.equal(await page.locator('.live2d-host').getAttribute('data-fps'),'30');await page.getByRole('button',{name:'阅读设置',exact:true}).click();assert.equal(await page.locator('.story-stage').getAttribute('data-paused'),'true');await page.getByLabel('渲染档位').selectOption('quality');await page.getByRole('button',{name:'关闭',exact:true}).click();assert.equal(await page.locator('.live2d-host').getAttribute('data-fps'),'60');await fs.mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/personal-player.png'});assert.deepEqual(errors,[]);console.log(JSON.stringify({personalEntries:catalog.length,chapters:jobs.map(j=>({id:j.story.entry.id,lines:j.story.lines.length,models:j.story.live2d.length,missing:j.missing.length})),renderProfiles:true}));}finally{await browser.close();}
