import {chromium} from '@playwright/test';import express from 'express';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {normalizeStory} from '../server/story.js';
const main={id:'main-idol-1-1',type:'main',unit:'idol',chapterNo:1,episode:1,title:'测试主线',cover:'blank.png'};
const events=Array.from({length:100},(_,i)=>[1,2].map(episode=>({id:`event-${i+1}-${episode}`,type:'event',unit:'event',eventId:i+1,eventName:`活动 ${i+1}`,episode,title:`对白 ${episode}`,cover:'blank.png'}))).flat();
const personal=[1,2].map(episode=>({id:`card-${episode}`,type:'personal',personalType:'card',groupId:'card-1',characterId:1,characterName:'一歌',unit:'light_sound',episode,chapter:'卡片剧情',title:`个人对白 ${episode}`,cover:'blank.png'}));
const story={...normalizeStory({ScenarioId:'presentation',TalkData:[{Body:'测试对白',WindowDisplayName:'一歌'}],Snippets:[{Action:1,ReferenceIndex:0}]}),entry:main,region:'jp',live2d:[]};
const app=express();app.get('/api/catalog',(req,res)=>res.json(req.query.type==='personal'?personal:[main,...events]));app.get('/api/cast/:id',(req,res)=>res.json({total:1,characters:[],bgm:req.params.id.startsWith('event-')?'bgm00007':''}));app.get('/api/resources',(_req,res)=>res.json({count:0,bytes:0,items:[]}));app.get('/api/downloads',(_req,res)=>res.json({tasks:[],paused:true,running:false}));app.post('/api/prepare/:id',(_req,res)=>res.json({key:'fixture'}));app.get('/api/jobs/:id',(_req,res)=>res.json({status:'ready',missing:[],story}));app.use('/assets/jp',(_req,res)=>res.status(404).end());app.use(express.static('dist'));
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const browser=await chromium.launch();
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('sekai.settings',JSON.stringify({bgm:50,speed:0,live2d:false}));localStorage.setItem('sekai.saves',JSON.stringify({'1':{entry:{title:'已有存档',cover:'blank.png'},region:'jp',index:3,text:'原存档保持不变',speaker:'一歌',date:'2026-10-01T00:00:00Z'}}));window.testAudio=[];window.Audio=class{constructor(src){this.src=src;this.paused=true;this.currentTime=0;this.dataset={};window.testAudio.push(this);}play(){this.paused=false;this.currentTime++;return Promise.resolve();}pause(){this.paused=true;}removeAttribute(){this.src='';}load(){}};});
 await page.goto(`http://127.0.0.1:${server.address().port}`);await fs.mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/home-0.1.6.png'});
 await page.getByRole('button',{name:'设置',exact:true}).click();await page.waitForFunction(()=>window.testAudio.length===1&&window.testAudio[0].volume===.2&&!window.testAudio[0].paused);await page.getByRole('button',{name:'返回主界面',exact:true}).click();await page.waitForFunction(()=>window.testAudio[0].volume===.5);
 await page.getByRole('button',{name:'资源管理',exact:true}).click();await page.waitForFunction(()=>window.testAudio.length===1&&window.testAudio[0].volume===.2&&!window.testAudio[0].paused);await page.getByRole('button',{name:'返回主界面',exact:true}).click();
 await page.getByRole('button',{name:'读取存档',exact:true}).click();assert.equal(await page.locator('.save-card').count(),13);assert.ok((await page.locator('.save-browser').textContent()).includes('48 个存档位'));assert.ok((await page.locator('.save-browser').textContent()).includes('已有存档'));await page.getByRole('button',{name:'存档第 4 页',exact:true}).click();assert.ok((await page.locator('.save-number').allTextContents()).includes('48'));await page.screenshot({path:'artifacts/saves-0.1.6.png'});await page.getByRole('button',{name:'返回主界面',exact:true}).click();
 await page.getByRole('button',{name:'开始阅读',exact:true}).click();await page.getByRole('button',{name:'活动剧情',exact:true}).click();await page.waitForFunction(()=>window.testAudio.at(-1).src.includes('bgm00007'));
 await page.evaluate(()=>{const node=document.querySelector('.directory-scroll');window.previousDirectory=node;node.scrollTop=350;node.dispatchEvent(new Event('scroll'));});const scroll=await page.locator('.directory-scroll').evaluate(e=>e.scrollTop);await page.locator('.directory-scroll button').nth(6).evaluate(e=>e.click());assert.equal(await page.locator('.directory-scroll').evaluate(e=>e===window.previousDirectory),true);assert.equal(await page.locator('.directory-scroll').evaluate(e=>e.scrollTop),scroll);
 await page.getByRole('button',{name:'返回主界面',exact:true}).click();await page.getByRole('button',{name:'开始阅读',exact:true}).click();assert.equal(await page.locator('.directory-scroll').evaluate(e=>e.scrollTop),scroll);assert.ok((await page.locator('.poster-title').textContent()).includes('活动 7'));
 await page.getByRole('button',{name:'个人剧情',exact:true}).click();await page.waitForFunction(()=>window.testAudio.at(-1).src.includes('bgm_area00001'));
 await page.locator('.episode-row').first().click();await page.locator('.dialogue').waitFor();await page.keyboard.press('Escape');await page.getByLabel('播放器画面比例').selectOption('cover');await page.keyboard.press('Escape');
 for(const size of [{width:1440,height:900},{width:1600,height:700},{width:600,height:900}]){await page.setViewportSize(size);const box=await page.locator('.player').boundingBox();assert.equal(Math.round(box.width),size.width);assert.equal(Math.round(box.height),size.height);const frame=await page.locator('.stage-visual-frame').boundingBox();assert.ok(Math.abs(frame.width/frame.height-16/9)<.01);assert.ok(await page.getByRole('button',{name:'阅读设置',exact:true}).isVisible());}
 await page.screenshot({path:'artifacts/player-cover-0.1.6.png'});await page.keyboard.press('Escape');await page.getByLabel('播放器画面比例').selectOption('contain');await page.keyboard.press('Escape');const fit=await page.locator('.player').boundingBox();assert.ok(Math.abs(fit.width/fit.height-16/9)<.01);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sekai.settings')).screenFit),'contain');assert.deepEqual(errors,[]);
 console.log(JSON.stringify({titleAndSaves:true,fortyEightSlots:true,oldSavesPreserved:true,menuMusicContinuousAndDucked:true,eventAndPersonalBgm:true,directoryIdentityAndScrollPreserved:true,returnRestoresSelection:true,cropWithoutStretch:true,fitAndSettingsPersist:true}));
}finally{await browser.close();await new Promise(r=>server.close(r));}
