import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base='http://127.0.0.1:3001',id='main-school_refusal-1-1';
await fetch(`${base}/api/prepare/${id}?region=cn`,{method:'POST'});let job;
for(let i=0;i<450;i++){job=await(await fetch(`${base}/api/jobs/cn%3A${id}`)).json();if(job.error)throw new Error(job.error);if(job.status==='ready')break;await new Promise(r=>setTimeout(r,400));}
assert.equal(job.status,'ready');assert.deepEqual(job.missing,[]);assert.deepEqual(job.warnings,[]);assert.match(job.story.lines[0].text,/妈妈/);
const b=await chromium.launch();try{
 const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[],failed=[],posterRequests=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push([r.status(),r.url()]);});p.on('request',r=>{if(/\/story\/(background|title_image)\//.test(r.url()))posterRequests.push(r.url());});
 await p.addInitScript(entry=>{localStorage.setItem('sekai.resume',JSON.stringify({entry,region:'cn',index:0}));localStorage.setItem('sekai.settings',JSON.stringify({region:'cn',voice:80,bgm:45,se:70,speed:0,live2d:true,autoDelay:500}));window.__media=[];const Original=window.Audio;window.Audio=function(...args){const a=new Original(...args);window.__media.push(a);return a;};window.Audio.prototype=Original.prototype;window.__contexts=[];const AC=window.AudioContext;window.AudioContext=function(...args){const c=new AC(...args);window.__contexts.push(c);return c;};window.AudioContext.prototype=AC.prototype;},job.story.entry);
 await p.goto(base);await p.getByRole('button',{name:'继续故事',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.fullscreen-text')?.textContent.includes('我很喜欢妈妈'),null,{timeout:60000});
 await p.waitForFunction(()=>window.__media.some(a=>!a.loop&&!a.paused&&a.currentTime>.1&&a.volume>.5));assert.ok(await p.evaluate(()=>window.__contexts.some(c=>c.state==='running')));
 const bg=await p.locator('.stage-background').evaluate(el=>getComputedStyle(el).backgroundImage.match(/url\("?([^"\)]+)/)?.[1]);assert.ok(bg.includes('/assets/cn/'));await p.evaluate(async src=>{const i=new Image();i.src=src;await i.decode();if(i.naturalWidth<1000)throw new Error('Background resolution too small');},bg);
 await fs.mkdir('artifacts',{recursive:true});await p.screenshot({path:'artifacts/cn-opening-fixed.png'});
 await p.getByRole('button',{name:'跳转',exact:true}).click();const target=job.story.lines.findIndex(l=>l.kind!=='fullscreen'&&l.background==='bg_e000102'&&l.bgm);assert.ok(target>=0);await p.locator('.jump-list>button').nth(target).click();await p.locator('.dialogue').waitFor();assert.equal(await p.locator('.fullscreen-text').count(),0);assert.equal(await p.locator('.stage-cover').evaluate(el=>el.style.opacity),'0');await p.waitForFunction(()=>window.__media.some(a=>a.loop&&!a.paused&&a.currentTime>.1&&a.volume>0));
 await p.screenshot({path:'artifacts/cn-scene-fixed.png'});await p.getByRole('button',{name:'返回主界面'}).click();await p.getByRole('button',{name:'开始阅读',exact:true}).click();await p.waitForFunction(()=>{const i=document.querySelector('.poster-image');return i?.complete&&i.naturalWidth>1000;});await p.waitForFunction(()=>{const i=document.querySelector('.poster-characters');return i?.complete&&i.naturalWidth>1000&&getComputedStyle(i).display!=='none';});assert.equal(new Set(posterRequests.map(u=>u.match(/main_[^/]+/)?.[0])).size,1,'only selected main-story poster was requested');
 await p.getByRole('button',{name:'25时，在Nightcord。',exact:true}).click();await p.waitForFunction(()=>{const i=document.querySelector('.poster-characters');return i?.src.includes('main_schoolrefusal')&&i.complete&&i.naturalWidth>1000&&getComputedStyle(i).display!=='none';});await p.screenshot({path:'artifacts/cn-main-cover-fixed.png'});
 const response=await fetch(base+'/assets/cn/sound/scenario/voice/nightcode_01_00/voice_op_night0_01_17.mp3',{headers:{Range:'bytes=0-99'}});assert.equal(response.status,206);assert.equal(response.headers.get('x-sekai-resource-region'),'jp');assert.equal((await response.arrayBuffer()).byteLength,100);
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log(JSON.stringify({region:'cn',lines:job.story.lines.length,resources:job.total,missing:job.missing,checks:'Original regional text, nonzero voice and BGM playback, unlocked audio context, real background decode, dialogue after narration, on-demand main covers and media range passed'}));
}finally{await b.close();}
