import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base='http://127.0.0.1:3001';
const catalog=await (await fetch(base+'/api/catalog?region=jp')).json();
const entry=catalog.find(e=>e.id==='main-idol-1-2');assert.ok(entry);
await fetch(base+'/api/prepare/'+entry.id+'?region=jp',{method:'POST'});
let job;
for(let tries=0;tries<300;tries++){
 job=await (await fetch(base+'/api/jobs/'+encodeURIComponent('jp:'+entry.id))).json();
 if(job.error)throw new Error(job.error);
 if(job.status==='ready')break;
 await new Promise(resolve=>setTimeout(resolve,500));
}
assert.equal(job.status,'ready');assert.ok(job.story.lines.length>10);
const browser=await chromium.launch();
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({entry})=>{
  if(!localStorage.getItem('sekai.resume'))localStorage.setItem('sekai.resume',JSON.stringify({entry,index:0,region:'jp'}));
  if(!localStorage.getItem('sekai.settings'))localStorage.setItem('sekai.settings',JSON.stringify({region:'jp',speed:10,autoDelay:500,bgm:0,voice:0,font:24}));
 },{entry});
 await page.goto(base);await page.locator('.title-menu').waitFor();
 await fs.mkdir('artifacts',{recursive:true});
 await page.screenshot({path:'artifacts/home.png',fullPage:true});
 await page.getByRole('button',{name:'继续故事',exact:true}).click();
 await page.locator('.dialogue').waitFor({timeout:60000});
 assert.ok(job.story.live2d.length>=2,'real Live2D manifests loaded');
 await page.waitForFunction(()=>document.querySelector('.live2d-host canvas')&&document.querySelector('.story-stage')?.dataset.ready==='true');
 const loadedModels=Number(await page.locator('.live2d-host').getAttribute('data-models'));
 assert.ok(loadedModels>=1,'visible models instantiated by Cubism');
 assert.ok(loadedModels<job.story.live2d.length,'future characters are loaded when they appear');
 await page.getByRole('button',{name:'跳转',exact:true}).click();
 await page.locator('.jump-list>button').nth(10).click();
 assert.ok((await page.locator('.player-top').textContent()).includes('11 /'));
 await page.getByRole('button',{name:'快进',exact:true}).click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('sekai.resume')).index>10);
 await page.getByRole('button',{name:'快进',exact:true}).click();
 await page.getByRole('button',{name:'跳转',exact:true}).click();
 await page.locator('.jump-list>button').nth(10).click();
 await page.getByRole('button',{name:'存档',exact:true}).click();
 await page.locator('.save-card').nth(1).getByRole('button',{name:'保存',exact:true}).click();
 await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.locator('.scene-click').click({position:{x:500,y:300}});
 await page.getByRole('button',{name:'读档',exact:true}).click();
 await page.locator('.save-card').nth(1).getByRole('button',{name:'读取',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.overlay').length===0);
 await page.waitForFunction(()=>document.querySelector('.story-stage')?.dataset.ready==='true'&&!document.querySelector('.stage-loading'));
 assert.ok((await page.locator('.player-top').textContent()).includes('11 /'));
 await page.screenshot({path:'artifacts/player.png',fullPage:true});
 assert.equal(await page.locator('.story-stage').getAttribute('data-actors'),'1');
 await page.reload();await page.getByRole('button',{name:'继续故事',exact:true}).click();await page.locator('.dialogue').waitFor();
 assert.ok((await page.locator('.player-top').textContent()).includes('11 /'));
 await page.getByRole('button',{name:'返回主界面'}).click();
 await page.getByRole('button',{name:'开始阅读',exact:false}).click();
 await page.getByRole('button',{name:'MORE MORE JUMP!',exact:true}).click();
 await page.getByRole('button',{name:'活动剧情',exact:true}).click();
 assert.ok(await page.locator('.chapter-card').count()>0);
 await page.getByRole('button',{name:'返回主界面',exact:true}).click();
 await page.getByRole('button',{name:'设置',exact:true}).first().click();
 await page.getByText('文字出现间隔',{exact:true}).locator('..').locator('..').locator('input').fill('20');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sekai.settings')).speed),20);
 await page.getByRole('button',{name:'暗色',exact:true}).click();
 assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');
 await page.reload();await page.getByRole('button',{name:'开始阅读',exact:true}).click();
 assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');
 await page.locator('.episode-row').first().waitFor();
 await page.screenshot({path:'artifacts/chapters-dark.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'返回主界面',exact:true}).click();
 await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({catalog:catalog.length,lines:job.story.lines.length,media:job.total,models:job.story.live2d.length,missing:job.missing.length,warnings:job.warnings,browserChecks:'Live2D, navigation, jump, fast-forward, save/load, reload, filters, dark theme persistence, settings, mobile passed'}));
}finally{await browser.close();}
