import React,{useEffect,useMemo,useState,useRef} from 'react';
import {Play,Check,Search,RotateCcw,ChevronRight,BookOpen} from 'lucide-react';
import CastBadges from './CastBadges';import {chapterStatus} from './read-state';
import {unitBgmPath,titleBgmPath,storyBgmPath} from '../server/unit-bgm.js';
export default function ChapterLibrary({catalog,region,units,type,setType,unit,setUnit,search,setSearch,loading,refresh,progress,history={},onMarkRead,openStory,onHome,bgmVolume=45,audioPaused=false,onMusicChange,retainedState={}}){
 const [selected,setSelected]=useState(retainedState.selected || ''),[character,setCharacter]=useState(retainedState.character || 'all'),[personalType,setPersonalType]=useState(retainedState.personalType || 'card'),[readFilter,setReadFilter]=useState(retainedState.readFilter || 'all'),[limit,setLimit]=useState(retainedState.limit || 80),[casts,setCasts]=useState({});
 const people=useMemo(()=>[...new Map(catalog.filter(e=>e.type==='personal').map(e=>[e.characterId,e.characterName])).entries()],[catalog]);
 const groups=useMemo(()=>{const map=new Map();for(const e of catalog){if(e.type!==type || (type==='personal'&&(e.personalType!==personalType||(character!=='all'&&e.characterId!==Number(character)))) || (type==='main'&&unit!=='all'&&e.unit!==unit))continue;if(!`${e.title} ${e.chapter} ${e.characterName || ''} ${units[e.unit] || ''}`.toLowerCase().includes(search.toLowerCase()))continue;const key=e.type==='personal'?e.groupId:e.type==='main'?`${e.unit}:${e.chapterNo || e.chapterTitle || e.chapter}`:`event:${e.eventId || e.chapter}`;if(!map.has(key))map.set(key,{key,title:e.type==='personal'?e.characterName:e.type==='event'?e.eventName || e.chapter:units[e.unit] || e.chapter,chapter:e.chapter,unit:e.unit,episodes:[]});map.get(key).episodes.push(e);}return [...map.values()].filter(g=>readFilter==='all'||(readFilter==='read')===g.episodes.every(e=>chapterStatus(e,region,progress,history).complete));},[catalog,type,unit,search,character,personalType,readFilter,progress,history]);
 useEffect(()=>{if(!groups.some(g=>g.key===selected))setSelected(groups[0]?.key || '');},[groups]);
 const firstFilter=useRef(true);
 useEffect(()=>{if(firstFilter.current){firstFilter.current=false;return;}setLimit(80);},[type,unit,search,character,personalType,readFilter]);
 const group=groups.find(g=>g.key===selected) || groups[0],representative=group?.episodes.find(e=>e.episode===2) || group?.episodes[0];
 const eventBgm=representative?casts[region+':'+representative.id]?.bgm:'';
 const music=type==='event'?storyBgmPath(eventBgm):unitBgmPath(type==='main'&&unit!=='all'?unit:group?.unit) || titleBgmPath;
 useEffect(()=>{onMusicChange?.(music);},[music,onMusicChange]);
 useEffect(()=>{Object.assign(retainedState,{selected,character,personalType,readFilter,limit});},[selected,character,personalType,readFilter,limit]);
 useEffect(()=>{const nodes=['main','.directory-scroll','.episode-list'];nodes.forEach(selector=>{const node=document.querySelector(selector);if(node&&retainedState.scroll?.[selector])node.scrollTop=retainedState.scroll[selector];});const remember=()=>{retainedState.scroll=Object.fromEntries(nodes.map(selector=>[selector,document.querySelector(selector)?.scrollTop || 0]));};document.addEventListener('scroll',remember,true);return()=>document.removeEventListener('scroll',remember,true);},[]);
 useEffect(()=>{if(!group)return;let cancelled=false;const controller=new AbortController();(async()=>{let cursor=0;await Promise.all(Array.from({length:2},async()=>{while(cursor<group.episodes.length&&!cancelled){const e=group.episodes[cursor++],key=region+':'+e.id;if(casts[key])continue;try{const response=await fetch(`/api/cast/${e.id}?region=${region}`,{signal:controller.signal});if(!response.ok)throw new Error();const data=await response.json();if(!cancelled)setCasts(c=>({...c,[key]:data}));}catch{if(!cancelled)setCasts(c=>({...c,[key]:{error:true,characters:[]}}));}}}));})();return()=>{cancelled=true;controller.abort();};},[group?.key,region]);
 const artwork=group?.unit==='piapro'?'piapro-story-chapter':'main_'+({light_sound:'lightsound',school_refusal:'schoolrefusal',theme_park:'themepark'}[group?.unit] || group?.unit);
 return <section className="content library-content vn-library">
  <div className="library-heading"><div><span>Story</span><h1>剧情选择</h1></div><nav><button onClick={refresh} disabled={loading}><RotateCcw size={13}/>同步目录</button><button onClick={onHome}>返回主界面</button></nav></div>
  <div className="library-filterbar"><div className="tabs">{[['main','主线剧情'],['event','活动剧情'],['personal','个人剧情']].map(([v,l])=><button key={v} className={type===v?'selected':''} onClick={()=>setType(v)}>{l}</button>)}</div><label className="search"><Search size={15}/><input placeholder="搜索活动名称、章节或标题…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="已读筛选" value={readFilter} onChange={e=>setReadFilter(e.target.value)}><option value="all">全部故事</option><option value="unread">未读故事</option><option value="read">已读故事</option></select></div>
  {type==='main'&&<div className="unit-filters">{Object.entries(units).map(([v,l])=><button key={v} className={unit===v?'selected':''} onClick={()=>setUnit(v)}>{l}</button>)}</div>}
  {type==='personal'&&<div className="personal-filters"><label>剧情类型<select aria-label="个人剧情类型" value={personalType} onChange={e=>setPersonalType(e.target.value)}><option value="card">卡片剧情 · 前篇 / 后篇</option><option value="profile">角色介绍</option></select></label><label>角色<select aria-label="剧情角色" value={character} onChange={e=>setCharacter(e.target.value)}><option value="all">全部角色</option>{people.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div>}
  <div className="library-meta"><span>{loading?'同步中…':`${groups.length} 个故事合集`}</span><span>{region.toUpperCase()} · 已读记录保存在本机</span></div>
  {!!group&&<div className="library-grid"><aside className="story-directory"><h2>STORY INDEX</h2><div className="directory-scroll">{groups.slice(0,Math.max(limit,groups.findIndex(g=>g.key===selected)+1)).map((g,i)=>{const read=g.episodes.filter(e=>chapterStatus(e,region,progress,history).complete).length;return <button key={g.key} className={g.key===group.key?'current':''} onClick={()=>setSelected(g.key)}><small>{String(i+1).padStart(3,'0')} · {read===g.episodes.length?'已读':`${read} / ${g.episodes.length} 已读`}</small><b>{g.title}</b>{type==='personal'&&<span>{g.chapter}</span>}</button>;})}{limit<groups.length&&<button className="more-stories" onClick={()=>setLimit(n=>n+80)}>显示更多故事</button>}</div></aside>
   <div className="collection-poster"><img key={region+':'+representative.id} className="poster-image" src={`/assets/${region}/${representative.poster || (type==='main'?`story/background/${artwork}/background.webp`:representative.cover)}`} alt="" onError={e=>{if(!e.target.dataset.fallback){e.target.dataset.fallback='true';e.target.src=`/assets/${region}/${representative.cover}`;}}}/>{type==='event'&&representative.posterTitle&&<img className="event-poster-title" src={`/assets/${region}/${representative.posterTitle}`} alt="" onError={e=>e.target.style.display='none'}/>} {type==='main'&&<img key={region+':'+representative.id} className="poster-characters" src={`/assets/${region}/${representative.posterTitle}`} alt={group.title} onError={e=>e.target.style.display='none'}/>}<div className="poster-scrim"/><div className="poster-top"><span>{type==='main'?'MAIN STORY':type==='personal'?'PERSONAL STORY':'EVENT STORY'}</span><BookOpen size={17}/></div><div className="poster-title"><small>想いが生まれる、その場所へ。</small><h2>{group.title}</h2>{type==='personal'&&<p>{group.chapter}</p>}<button onClick={()=>openStory(group.episodes[0])}><Play size={14}/>从第一话开始</button></div><div className="poster-bottom"><span>{group.episodes.length} 段故事</span><span>SEKAI NOVEL</span></div></div>
   <div className="episode-panel"><div className="episode-heading"><h2>章节 · EPISODES</h2><span>{group.episodes.length}</span></div><div className="episode-list">{group.episodes.map((e,i)=>{const data=casts[region+':'+e.id],p=chapterStatus(e,region,{...progress,[region+':'+e.id]:{...progress[region+':'+e.id],total:progress[region+':'+e.id]?.total || data?.total}},history);return <div className={'episode-item '+(p.complete?'is-read':'')} key={e.id}><button className="episode-row chapter-card" onClick={()=>openStory(e)}><span className="episode-number">{String(type==='main'?i:e.episode).padStart(2,'0')}</span><div className="episode-copy"><small>{type==='personal'?(e.personalType==='profile'?'角色介绍':e.episode===1?'前篇':'后篇'):type==='main'&&i===0?'OPENING':`EPISODE ${e.episode}`}</small><h3>{e.title}</h3><p>{p.complete?<><Check size={12}/>已读</>:p.seen?`已读 ${p.seen}${p.total?' / '+p.total:''} 句`:'未读 · 下载并阅读'}</p>{data?<>{data.error?<span className="cast-loading">角色信息暂不可用</span>:<CastBadges characters={data.characters} region={region}/>}</>:<span className="cast-loading">按需读取出场角色…</span>}</div><ChevronRight size={16}/></button><button className="read-toggle" aria-label={`${p.complete?'标记未读':'标记已读'}：${e.title}`} aria-pressed={p.complete} onClick={()=>onMarkRead?.(e,!p.complete,data?.total)}>{p.complete?'✓ 已读':'◇ 标记已读'}</button></div>;})}</div><div className="collection-selector"><label>章节合集<select aria-label="章节合集" value={group.key} onChange={e=>setSelected(e.target.value)}>{groups.map(g=><option key={g.key} value={g.key}>{g.title}{type==='personal'?' · '+g.chapter:''}</option>)}</select></label></div></div>
  </div>}
  {!loading&&!groups.length&&<div className="empty">没有符合筛选条件的故事。</div>}
 </section>;
}
