import React from 'react';
import ThemeSettings from './ThemeSettings';
import ReaderAppearance from './ReaderAppearance';
import DesktopSettings from './DesktopSettings';
import ShortcutHelp from './ShortcutHelp';
import PlayerLayoutSetting from './PlayerLayoutSetting';
export default function GameSettings({settings,setSettings,story,defaults,compact,onClose,full,onSave,onLoad,onHome}){
 const change=(key,value)=>setSettings(s=>({...s,[key]:value}));
 async function windowMode(fullscreen){if(!fullscreen&&document.fullscreenElement)await document.exitFullscreen();if(window.sekaiDesktop)await window.sekaiDesktop.setFullscreen(fullscreen);else if(fullscreen&&!document.fullscreenElement)full?.();}
 const range=(key,title,min,max,unit='%',description='')=><label className="setting" key={key}><div><b>{title}</b>{description&&<p>{description}</p>}</div><div className="range"><input aria-label={title} type="range" min={min} max={max} step={key==='autoDelay'?100:1} value={settings[key] ?? defaults[key]} onChange={e=>change(key,+e.target.value)}/><output>{settings[key] ?? defaults[key]}{unit}</output></div></label>;
 return <section className={'game-options '+(compact?'in-story':'')}>
  <div className="options-heading"><div><span>Option</span><h1>游戏设置</h1></div><nav>{onSave&&<button onClick={onSave}>SAVE · 存档</button>}{onLoad&&<button onClick={onLoad}>LOAD · 读档</button>}{compact&&<button onClick={onClose}>返回剧情</button>}{window.sekaiDesktop&&<button onClick={()=>window.sekaiDesktop.quit()}>退出游戏</button>}<button onClick={compact?onHome:onClose}>返回主界面</button></nav></div>
  <div className="options-frame"><div className="options-toolbar"><span>✦ 以你喜欢的节奏，阅读世界</span><button onClick={()=>setSettings({...defaults})}>恢复默认</button></div>
  <div className="options-columns">
   <div className="options-column"><h2>系统设置<small>SYSTEM</small></h2><div className="column-scroll"><div className="setting"><b>画面模式</b><div className="theme-options"><button onClick={()=>windowMode(false)}>窗口模式</button><button onClick={()=>windowMode(true)}>全屏模式</button></div></div><PlayerLayoutSetting settings={settings} setSettings={setSettings}/><ThemeSettings section="system" settings={settings} setSettings={setSettings}/>{!compact&&<label className="setting"><b>剧情服务器</b><select aria-label="剧情服务器" value={settings.region} onChange={e=>change('region',e.target.value)}>{[['jp','日服 · 日本語'],['cn','国服 · 简体中文'],['tw','台服 · 繁體中文'],['en','国际服 · English'],['kr','韩服 · 한국어']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}<label className="setting"><b>鼠标右键功能</b><select aria-label="鼠标右键功能" value={settings.rightClick || 'hide'} onChange={e=>change('rightClick',e.target.value)}><option value="hide">隐藏 / 显示对白</option><option value="settings">展开设置菜单</option></select></label><ShortcutHelp/><DesktopSettings/></div></div>
   <div className="options-column"><h2>声音设置<small>SOUND</small></h2><div className="column-scroll">{range('bgm','BGM 音量',0,100)}{range('voice','角色语音音量',0,100)}{range('se','场景音效音量',0,100)}<p className="column-note">点击或按 Space 先补全文字，再次操作中断配音并快速进入下一句，略过中间演出；自动模式等待语音结束。</p><p className="column-note">配音按钮可从头重播当前对白；Backlog 可重播已读对白。</p></div></div>
   <div className="options-column"><h2>文本信息设置<small>TEXT</small></h2><div className="column-scroll">{range('speed','文字出现间隔',0,150,'ms','0 为立即显示')}{range('autoDelay','自动阅读等待',500,6000,'ms','配音结束后再计时')}{range('font','对白字号',18,36,'px')}{range('dialogueOpacity','对白遮罩透明度',0,100)}<details className="advanced-text"><summary>高级文字节奏</summary>{range('lineDelay','每句起始等待',0,3000,'ms')}{range('punctuationDelay','标点停顿',0,1000,'ms')}</details><ReaderAppearance settings={settings} setSettings={setSettings} story={story}/><div className="dialogue-preview" style={{background:`rgba(8,20,35,${(settings.dialogueOpacity ?? 78)/100})`,fontSize:settings.font}}>每一个「想要」，都通向一个新的世界。</div></div></div>
   <div className="options-column"><h2>演出效果设置<small>PERFORMANCE</small></h2><div className="column-scroll"><ThemeSettings section="effects" settings={settings} setSettings={setSettings}/><p className="column-note">模型在角色出场时载入，仅更新可见角色。节能档降低画布分辨率与帧率。</p></div></div>
  </div><div className="options-bottom"><span>SEKAI NOVEL · CONFIGURATION</span><span>设置自动保存</span></div></div>
 </section>;
}
