import React from 'react';
import {ChevronLeft,ChevronRight,Maximize,Settings,Play,Pause,FastForward,Save,BookOpen,List,EyeOff,Volume2} from 'lucide-react';
import StoryStage from './StoryStage';
import {speakerColor,fontFamily} from './ReaderAppearance';
import {shortcutHints} from './shortcuts';
export default function NovelPlayer({story,line,index,settings,read,visible,text,hidden,setHidden,auto,setAuto,skip,setSkip,go,next,modal,background,setModal,nav,full,voicesRef,onBusy,onWarning,onSceneChange,busy,restore}){
 return <section className={'vn-screen screen-'+(settings.screenFit || 'contain')} style={{'--speaker-color':speakerColor(line,settings),'--novel-font':fontFamily(settings),'--dialogue-opacity':(settings.dialogueOpacity ?? 78)/100}}><div className="player" onContextMenu={e=>{e.preventDefault();if(settings.rightClick==='settings')setModal('settings');else setHidden(v=>!v);}}>
 <StoryStage story={story} line={line} index={index} restore={restore} skip={skip} paused={!!modal || background} settings={settings} voicesRef={voicesRef} onBusy={onBusy} onWarning={onWarning} onSceneChange={onSceneChange} textVisible={visible}/>
 <button className="scene-click" aria-label="推进剧情" onClick={()=>hidden?setHidden(false):next()}/>
 <div className="player-top"><button className="glass" onClick={()=>nav('home')}><ChevronLeft size={17}/>返回主界面</button><span>{story.entry.title}<small>{index+1} / {story.lines.length}<em className="line-read-mark">{read?'已读':'未读'}</em></small></span><button className="glass" title={shortcutHints.fullscreen} onClick={full} aria-label="全屏"><Maximize size={17}/></button></div>
 {!hidden&&!busy&&line.kind!=='fullscreen'&&<div className="dialogue"><div className="speaker">{line.speaker}</div><button className="dialogue-body" style={{fontSize:settings.font}} onClick={next}>{text.slice(0,visible)}<span className={'advance '+(visible>=text.length?' ready':'')}>▸</span></button></div>}
 {hidden&&<button className="show-dialogue glass" onClick={()=>setHidden(false)}>显示对白</button>}
 <div className="vn-controls player-controls"><button title={shortcutHints.previous} onClick={()=>go(index-1)} disabled={!index}><ChevronLeft size={17}/><span>上一句</span></button><button title={shortcutHints.next} onClick={next}><ChevronRight size={17}/><span>下一句</span></button><button title={shortcutHints.auto} className={auto?'on':''} onClick={()=>{setAuto(!auto);setSkip(false);}}>{auto?<Pause size={16}/>:<Play size={16}/>}<span>自动</span></button><button title={shortcutHints.skip} className={skip?'on':''} onClick={()=>{setSkip(!skip);setAuto(false);}}><FastForward size={17}/><span>快进</span></button><i/>
 <button title={shortcutHints.save} onClick={()=>setModal('save')}><Save size={16}/><span>存档</span></button><button title={shortcutHints.load} onClick={()=>setModal('load')}><BookOpen size={16}/><span>读档</span></button><button title={shortcutHints.log} onClick={()=>{setAuto(false);setSkip(false);setModal('log');}}><List size={17}/><span>Backlog</span></button><button title={shortcutHints.jump} onClick={()=>setModal('jump')}><ChevronRight size={16}/><span>跳转</span></button><button title={shortcutHints.voice} onClick={()=>voicesRef.current.forEach(a=>{a.currentTime=0;a.play().catch(()=>{});})}><Volume2 size={16}/><span>配音</span></button><button title={shortcutHints.hide} onClick={()=>setHidden(v=>!v)}><EyeOff size={16}/><span>隐藏</span></button><button title={shortcutHints.settings} onClick={()=>setModal('settings')} aria-label="阅读设置"><Settings size={17}/><span>设置</span></button></div>
 </div></section>;
}
