import React,{useEffect,useState} from 'react';
const fonts={sans:'"Noto Sans CJK SC", "Microsoft YaHei", sans-serif',serif:'"Noto Serif CJK SC", "Songti SC", "SimSun", serif',system:'system-ui, sans-serif',custom:'"SekaiCustomFont", "Microsoft YaHei", sans-serif'};
export const fontFamily=s=>fonts[s.fontFamily] || fonts.sans;
export const speakerKey=l=>String(l?.characters?.[0]?.Character2dId || l?.characters?.[0]?.CharacterId || l?.speaker || '旁白');
export const speakerColor=(l,s)=>s.characterColors?.[speakerKey(l)] || s.characterColors?.[l?.speaker] || '#7ee5dd';
function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('sekai-fonts',1);r.onupgradeneeded=()=>r.result.createObjectStore('fonts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function installFont(data){const face=new FontFace('SekaiCustomFont',data);await face.load();for(const old of document.fonts)if(old.family==='SekaiCustomFont')document.fonts.delete(old);document.fonts.add(face);}
export async function restoreFont(){try{const db=await database();const data=await new Promise((resolve,reject)=>{const r=db.transaction('fonts').objectStore('fonts').get('custom');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});db.close();if(data)await installFont(data);}catch{}}
export default function ReaderAppearance({settings,setSettings,story}){
 const characters=[...new Map((story?.lines || []).map(l=>[speakerKey(l),{id:speakerKey(l),name:l.speaker}])).values()];
 const [character,setCharacter]=useState(characters[0]?.id || '旁白'),[status,setStatus]=useState('');
 useEffect(()=>{if(characters.length&&!characters.some(c=>c.id===character))setCharacter(characters[0].id);},[story]);
 async function upload(file){if(!file)return;try{const data=await file.arrayBuffer();await installFont(data);const db=await database();await new Promise((resolve,reject)=>{const tx=db.transaction('fonts','readwrite');tx.objectStore('fonts').put(data,'custom');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();setSettings(s=>({...s,fontFamily:'custom',fontName:file.name}));setStatus('字体已保存');}catch{setStatus('字体无法载入，请选择 TTF、OTF 或 WOFF 文件');}}
 return <><label className="setting"><div><b>对白字体</b><p>本地字体会保存在当前浏览器，重新打开仍可使用。</p></div><select aria-label="对白字体" value={settings.fontFamily || 'sans'} onChange={e=>setSettings(s=>({...s,fontFamily:e.target.value}))}><option value="sans">黑体</option><option value="serif">宋体 / 明朝体</option><option value="system">系统字体</option>{settings.fontName&&<option value="custom">{settings.fontName}</option>}</select></label>
 <label className="setting"><div><b>导入自定义字体</b><p>{status || settings.fontName || 'TTF · OTF · WOFF · WOFF2'}</p></div><input aria-label="导入自定义字体" type="file" accept=".ttf,.otf,.woff,.woff2" onChange={e=>upload(e.target.files[0])}/></label>
 <div className="setting"><div><b>角色主题色</b><p>用于角色姓名、对白边线和 Backlog。打开章节后可选择该章角色。</p></div><div className="character-colors">{characters.length?<select aria-label="角色" value={character} onChange={e=>setCharacter(e.target.value)}>{characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>:<input aria-label="角色姓名" placeholder="输入剧情中的角色姓名" value={character} onChange={e=>setCharacter(e.target.value)}/>}<input aria-label="角色主题色" type="color" value={settings.characterColors?.[character] || '#7ee5dd'} onChange={e=>setSettings(s=>({...s,characterColors:{...s.characterColors,[character]:e.target.value}}))}/><button onClick={()=>setSettings(s=>{const colors={...s.characterColors};delete colors[character];return {...s,characterColors:colors};})}>重置</button></div></div></>;
}
