import React,{useEffect,useMemo,useState} from 'react';
const size=n=>n>=1073741824?(n/1073741824).toFixed(2)+' GB':n>=1048576?(n/1048576).toFixed(1)+' MB':n>=1024?(n/1024).toFixed(1)+' KB':n+' B';
const states={queued:'等待下载',downloading:'下载中',complete:'已缓存',partial:'部分缺失',failed:'下载失败',cancelled:'已取消',removed:'缓存已清理'};
const kinds={audio:'音频',image:'图片',live2d:'Live2D',video:'视频',script:'剧本',metadata:'目录 / 运行库',legacy:'旧缓存（未知来源）'};
async function api(url,body){const r=await fetch(url,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw new Error(data.error || '资源操作失败');return data;}
async function removeSelected(keys){const result={bytes:0,count:0};for(let n=0;n<keys.length;n+=5000){const deleted=await api('/api/resources/delete',{keys:keys.slice(n,n+5000)});result.bytes+=deleted.bytes;result.count+=deleted.count;}return result;}
export default function ResourceManager({region,onHome}){
 const [tab,setTab]=useState('download'),[type,setType]=useState('main'),[entries,setEntries]=useState([]),[search,setSearch]=useState(''),[selection,setSelection]=useState(new Set()),[queue,setQueue]=useState({tasks:[],paused:true}),[resources,setResources]=useState({items:[],bytes:0,count:0}),[keys,setKeys]=useState(new Set()),[kind,setKind]=useState('all'),[fileSearch,setFileSearch]=useState(''),[limit,setLimit]=useState(100),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[loading,setLoading]=useState(false);
 const refresh=async()=>{const [q,r]=await Promise.all([api('/api/downloads'),api('/api/resources')]);setQueue(q);setResources(r);};
 useEffect(()=>{let active=true;const tick=async()=>{try{const q=await api('/api/downloads');if(active)setQueue(q);}catch(e){if(active)setError(e.message);}};refresh().catch(e=>setError(e.message));const timer=setInterval(tick,1200);return()=>{active=false;clearInterval(timer);};},[]);
 useEffect(()=>{let active=true;api('/api/resources').then(r=>{if(active)setResources(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[queue.tasks.map(t=>t.status).join(',')]);
 useEffect(()=>{let active=true;setLoading(true);setSelection(new Set());setSearch('');api(`/api/catalog?region=${region}${type==='personal'?'&type=personal':''}`).then(data=>{if(active)setEntries(data.filter(e=>e.type===type));}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[region,type]);
 const filtered=useMemo(()=>entries.filter(e=>`${e.eventName || ''} ${e.chapter} ${e.title} ${e.characterName || ''} ${e.unit}`.toLowerCase().includes(search.toLowerCase())),[entries,search]);
 const files=resources.items.filter(i=>(kind==='all'||i.kind===kind)&&`${i.url} ${i.key} ${i.owners.join(' ')}`.toLowerCase().includes(fileSearch.toLowerCase()));
 const selectedFiles=resources.items.filter(i=>keys.has(i.key)),selectedBytes=selectedFiles.reduce((n,i)=>n+i.size,0),affected=new Set(selectedFiles.flatMap(i=>i.owners));
 const chapters=new Map();for(const i of resources.items)for(const owner of i.owners){if(!chapters.has(owner))chapters.set(owner,[]);chapters.get(owner).push(i);}
 const titles=new Map([...queue.tasks.map(t=>[t.key,t.entry]),...entries.map(e=>[region+':'+e.id,e])]);
 async function action(fn){setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const toggle=(id,setter)=>setter(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
 return <section className="resource-screen"><div className="library-heading"><div><span>Resource</span><h1>资源管理</h1></div><nav><button disabled={busy} onClick={()=>action(refresh)}>刷新占用</button><button onClick={onHome}>返回主界面</button></nav></div>
 <div className="resource-summary"><span>本地资源 <b>{size(resources.bytes)}</b></span><span><b>{resources.count}</b> 个文件</span><span><b>{chapters.size}</b> 个已关联章节</span><span>{region.toUpperCase()} · 共享资源只存一份</span></div>
 <div className="tabs resource-tabs">{[['download','批量下载'],['queue','下载队列'],['chapters','章节缓存'],['files','资源文件']].map(([v,l])=><button key={v} className={tab===v?'selected':''} onClick={()=>{setTab(v);setConfirm(false);}}>{l}</button>)}</div>
 {error&&<p className="resource-error" role="alert">{error}</p>}{notice&&<p className="resource-notice" role="status">{notice}</p>}
 {tab==='download'&&<><div className="resource-toolbar"><select aria-label="下载剧情类型" value={type} onChange={e=>setType(e.target.value)}><option value="main">主线剧情</option><option value="event">活动剧情</option><option value="personal">个人剧情</option></select><input aria-label="筛选下载章节" placeholder="活动名称、组合、角色、章节…" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>setSelection(new Set(filtered.slice(0,500).map(e=>e.id)))}>选择筛选结果（最多 500 章）</button><button onClick={()=>setSelection(new Set())}>取消选择</button><button disabled={busy||!selection.size} onClick={()=>action(async()=>{await api('/api/downloads',{region,ids:[...selection]});setNotice(`${selection.size} 个章节已加入下载队列`);setTab('queue');})}>下载所选 {selection.size} 章</button></div><p className="resource-note">下载剧本、背景、配音、音乐、封面、Live2D 与演出资源。首次下载所需空间取决于章节；完成后可离线阅读，缺失项可重试。</p><div className="resource-list">{loading?<p>正在读取目录…</p>:filtered.slice(0,500).map(e=><label className="download-chapter" key={e.id}><input type="checkbox" checked={selection.has(e.id)} onChange={()=>toggle(e.id,setSelection)}/><span><small>{e.eventName || e.characterName || e.chapter}</small><b>{e.title}</b></span><em>{states[queue.tasks.find(t=>t.key===region+':'+e.id)?.status] || '未加入队列'}</em></label>)}{filtered.length>500&&<p>显示前 500 章，共 {filtered.length} 章。请使用搜索缩小范围。</p>}</div></>}
 {tab==='queue'&&<><div className="resource-toolbar"><span>{queue.paused?'队列已暂停':queue.running?'正在下载':'队列空闲'}</span><button disabled={busy} onClick={()=>action(()=>api('/api/downloads/pause',{}))}>暂停队列</button><button disabled={busy} onClick={()=>action(()=>api('/api/downloads/resume',{}))}>继续 / 重试缺失</button><button disabled={busy} onClick={()=>action(()=>api('/api/downloads/clear',{}))}>取消待下载项</button></div><p className="resource-note">暂停或取消在当前章节完成后生效。关闭程序会保留队列，再次启动后点击“继续”恢复下载。</p><div className="resource-list">{queue.tasks.map(t=><article className="queue-item" key={t.key}><div><small>{t.region.toUpperCase()} · {t.entry.eventName || t.entry.chapter}</small><h3>{t.entry.title}</h3></div><span>{states[t.status]}{t.status==='downloading'?` · ${t.phase || '准备'} · ${t.done} / ${t.total}`:''}</span>{t.status==='downloading'&&<progress max={t.total || 1} value={t.done}/>}<p>{t.error || (t.status==='partial'?`缺少 ${t.missing || 0} 个音画资源；${t.warnings?.join('；') || ''}`:'')}</p></article>)}{!queue.tasks.length&&<p>选择章节后开始批量下载。</p>}</div></>}
 {tab==='chapters'&&<><p className="resource-note">按章节清理时保留与其他章节共享的文件。存档、已读记录与设置不受影响；需要时可重新下载。</p><div className="resource-list">{[...chapters].map(([owner,items])=>{const e=titles.get(owner),exclusive=items.filter(i=>i.owners.length===1);return <article className="queue-item" key={owner}><div><small>{owner}</small><h3>{e?.title || owner}</h3></div><span>{items.length} 个资源 · 含共享 {size(items.reduce((n,i)=>n+i.size,0))}</span><button disabled={!exclusive.length||busy} onClick={()=>{setKeys(new Set(exclusive.map(i=>i.key)));setConfirm(true);}}>清理独占资源 · {size(exclusive.reduce((n,i)=>n+i.size,0))}</button></article>;})}{!chapters.size&&<p>尚无关联章节。旧缓存可在“资源文件”中查看。</p>}</div></>}
 {tab==='files'&&<><div className="resource-toolbar"><select aria-label="资源类型" value={kind} onChange={e=>{setKind(e.target.value);setLimit(100);}}><option value="all">所有资源</option>{Object.entries(kinds).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input aria-label="搜索缓存资源" placeholder="资源路径、章节 ID 或文件标识…" value={fileSearch} onChange={e=>{setFileSearch(e.target.value);setLimit(100);}}/><button onClick={()=>setKeys(new Set(resources.items.map(i=>i.key)))}>全选文件</button><button onClick={()=>setKeys(new Set(files.map(i=>i.key)))}>选择筛选结果</button><span>已选 {selectedFiles.length} / {resources.count} 个文件</span><button onClick={()=>setKeys(new Set())}>取消选择</button><button disabled={!keys.size||busy} onClick={()=>setConfirm(true)}>清理所选 · {size(selectedBytes)}</button></div><div className="resource-list">{files.slice(0,limit).map(i=><label className="download-chapter resource-file" key={i.key}><input type="checkbox" checked={keys.has(i.key)} onChange={()=>toggle(i.key,setKeys)}/><span><small>{kinds[i.kind]} · {i.owners.length?'关联 '+i.owners.length+' 个章节':'未关联章节'}</small><b title={i.url || i.key}>{i.url?i.url.replace(/^https?:\/\/[^/]+\//,''):i.key}</b></span><em>{size(i.size)}</em></label>)}{limit<files.length&&<button onClick={()=>setLimit(n=>n+100)}>显示更多 · 共 {files.length} 个文件</button>}</div></>}
 {tab==='files'&&<div className="resource-toolbar"><button className="danger-button" disabled={busy||!resources.count} onClick={()=>setConfirm('all')}>一键清空缓存</button><span className="resource-note">包含所有服务器、共享资源和旧缓存；保留存档、已读记录、字体和设置。</span></div>}
 {confirm&&<div className="resource-confirm" role="dialog" aria-label="确认清理资源"><h3>{confirm==='all'?`清空全部 ${resources.count} 个缓存文件，释放 ${size(resources.bytes)}？`:`清理 ${selectedFiles.length} 个文件，释放 ${size(selectedBytes)}？`}</h3><p>{confirm==='all'?'已缓存章节需要重新下载，待下载项会取消。存档、已读记录、字体和设置将保留。':`涉及 ${affected.size} 个章节。删除共享资源可能需要为其他章节重新下载。未知来源的旧缓存无法判断所属章节。`}</p><button disabled={busy} onClick={()=>action(async()=>{const result=confirm==='all'?await api('/api/resources/clear',{confirm:'clear-cache'}):await removeSelected([...keys]);if(confirm==='all')await window.sekaiDesktop?.clearHttpCache?.();setConfirm(false);setKeys(new Set());setNotice(`已清理 ${result.count} 个资源，释放 ${size(result.bytes)}`);})}>{confirm==='all'?'确认清空缓存':'确认清理'}</button><button onClick={()=>setConfirm(false)}>取消</button></div>}
 </section>;
}
