import React,{useState} from 'react';
import {Bookmark,ChevronLeft,ChevronRight,Save,BookOpen,Trash2} from 'lucide-react';
const SLOT_COUNT=48,PAGE_SIZE=12;
export default function SaveGrid({saves,onSave,onLoad,onDelete}){
 const [page,setPage]=useState(0);
 function card(slot){const save=saves[slot],image=save?.background?`scenario/background/${save.background}/${save.background}.webp`:save?.entry?.poster || save?.entry?.cover;return <article className={'save-card '+(save?'occupied':'empty-slot')} key={slot}><div className="save-preview">{image&&<img src={`/assets/${save.region}/${image}`} alt="" loading="lazy" onError={e=>e.currentTarget.style.opacity=0}/>}<span className="save-number">{slot==='快速'?'QUICK':String(slot).padStart(2,'0')}</span><span className="save-region">{save?.region?.toUpperCase() || 'EMPTY'}</span>{!save&&<Bookmark size={24}/>}</div><div className="save-copy"><h3>{save?.entry?.title || '等待新的故事'}</h3><p>{save?`${save.speaker || '旁白'} · 第 ${save.index+1} 句`:'在此留下一段思念。'}</p>{save&&<blockquote>{save.text?.slice(0,75)}</blockquote>}<time>{save?new Date(save.date).toLocaleString('zh-CN'):'— —'}</time><div className="save-actions">{onSave&&<button onClick={()=>onSave(slot)} title={save?'覆盖此存档':'保存到此位置'}><Save size={13}/>保存</button>}{save&&<button onClick={()=>onLoad(save)}><BookOpen size={13}/>读取</button>}{save&&onDelete&&<button className="delete-save" onClick={()=>onDelete(slot)} aria-label={`删除存档 ${slot}`}><Trash2 size={13}/></button>}</div></div></article>;}
 return <div className="save-browser"><div className="save-pagination"><span>MEMORY ARCHIVE · {SLOT_COUNT} 个存档位 + 快速存档</span><nav><button onClick={()=>setPage(p=>Math.max(0,p-1))} disabled={!page} aria-label="上一页存档"><ChevronLeft size={15}/></button>{Array.from({length:SLOT_COUNT/PAGE_SIZE},(_,i)=><button key={i} aria-label={`存档第 ${i+1} 页`} aria-pressed={page===i} className={page===i?'selected':''} onClick={()=>setPage(i)}>{String(i+1).padStart(2,'0')}</button>)}<button onClick={()=>setPage(p=>Math.min(SLOT_COUNT/PAGE_SIZE-1,p+1))} disabled={page===SLOT_COUNT/PAGE_SIZE-1} aria-label="下一页存档"><ChevronRight size={15}/></button></nav></div><section className="quick-save-slot" aria-label="快速存档"><h2>QUICK SAVE · 快速存档</h2>{card('快速')}</section><div className="save-grid">{Array.from({length:PAGE_SIZE},(_,i)=>card(String(page*PAGE_SIZE+i+1)))}</div></div>;
}
export function SaveScreen({saves,onLoad,onDelete,onHome}){return <section className="content save-screen"><header className="memory-heading"><div><span>Memory</span><h1>思念的书签</h1><p>让世界，停在你珍藏的那一刻。</p></div><button onClick={onHome}>返回主界面</button></header><SaveGrid saves={saves} onLoad={onLoad} onDelete={onDelete}/></section>;}
